### ISSUE TITLE
Weights not displaying correctly

### ISSUE THREAD

**Issue by ShantanuVidwans** [dev-kasibhatla/krissues#11]
![Screenshot_2020-08-13-18-09-52-551_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90264078-337fbe00-de6e-11ea-91ea-96401caa75a4.jpg)
![Screenshot_2020-08-13-18-10-05-713_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90264083-34b0eb00-de6e-11ea-8c20-f9581c832281.jpg)
![Screenshot_2020-08-13-18-10-09-446_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90264085-35498180-de6e-11ea-98df-fc8e82a58d7d.jpg)

MIUI 11 6 inch

The text displaying the weight is out of box.

**Comment by dev-kasibhatla** [comment]
Thank you. I'll try to adjust it
