### ISSUE TITLE
Search Problem

### ISSUE THREAD

**Issue by ShantanuVidwans** [dev-kasibhatla/krissues#12]
![Screenshot_2020-08-13-18-05-57-157_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90264294-7d68a400-de6e-11ea-82b2-f1e417de0a5f.jpg)

MIUI 11 6 inch

Search not working properly. When i went for searching for big, it shows cucumbers.

**Comment by dev-kasibhatla** [comment]
**This is not an issue**
We are using a system of tags to make the search more meaningful
Cucumber has a tag called `koshimbir` since it is used in Maharashtian salads
