### ISSUE TITLE
Display isssue (a white border box showing up)

### ISSUE THREAD

**Issue by ShantanuVidwans** [dev-kasibhatla/krissues#13]
![Screenshot_2020-08-13-18-05-31-963_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90264529-db958700-de6e-11ea-9e9d-42bcec7029e1.jpg)

There is a white spacing all around the list section, can be seen on the circles regions.

**Comment by dev-kasibhatla** [comment]
Thank you I'll adjust the padding
