### ISSUE TITLE
fixing UI for landscape mode 

### ISSUE THREAD

**Issue by vedantkarle** [dev-kasibhatla/krissues#15]
1.The navbar is not scrollable for landscape mode
2.the edit item card is also not scrollable in landscape mode

**Comment by dev-kasibhatla** [comment]
Thank you very much for bringing this up!
I'll disable landscape rotation.

**Comment by dev-kasibhatla** [comment]
Why the long face @msvamp?

**Comment by msvamp** [comment]
The app should support landscape.

> I'll disable landscape rotation.

This is just an excuse for not making the app landscape-ready.

**Comment by dev-kasibhatla** [comment]
### I don't see why this app needs all that extra effort. 
1. A very small fraction of users will want landscape.
2. People are not going to use this app on tablets or chrome os.
3. Also, in the very limited time we have, I'd rather refine portrait experience than write patches for landscape
