### ISSUE TITLE
SUPER CRITICAL: Orders getting deleted

### ISSUE THREAD

**Issue by dev-kasibhatla** [dev-kasibhatla/krissues#16]
After changing phone number, or any other account information, orders are getting deleted.
This behaviour can also be seen when we just change the phone verification status from firebase console.

**Comment by dev-kasibhatla** [comment]
Fixed, but awaiting @msvamp 's confirmation

**Comment by msvamp** [comment]
Tested above mentioned behaviour in `App version 1.0.2 (release-15-08-20-14_13_30)` and the issue seems fixed.
