### ISSUE TITLE
Order not showing up after being placed

### ISSUE THREAD

**Issue by dev-kasibhatla** [dev-kasibhatla/krissues#20]
A strange issue has been occurring. 
The order won't place on WiFi, but will place on mobile data.
On WiFi, it won't place on sbi, but will place on hdfc. 
New information:
Order won't place on sbi with mobile data either

Now here's the confusing part:
Razorpay returns that the payment went through.
So `order successful callback` is being run. Yet, order is not visible.

**Comment by dev-kasibhatla** [comment]
New information: all orders appearing on firebase, but not to user, even after killing and restarting the app.

**Comment by msvamp** [comment]
I am unable to reproduce this issue on `Version 1.0.2 (release-16-08-20-12_41_39)`. Just updated the app, and tried placing 3 orders. All do appear in the _Orders_ section with the right status and amount.

> The order **won't place** on WiFi, but will place on mobile data.
> On WiFi, it **won't place** on sbi, but will place on hdfc.

> Order **won't place**

Do you mean the _Order placed successfully_ dialog doesn't appear at all or does the order just not appear in the _Orders_ section?

---

Also, there was a bug in `Version 1.0.2 (release-15-08-20-14_13_30)` using which I had been able to make orders not appear in the _Orders_ section (and also leave the cart untouched) even after a successful payment by pressing the _Back_ navigation button at the right time.  
Couldn't reproduce the issue in the new release - I can still prevent the cart from getting cleared after the payment, but can no longer stop the order from getting booked successfully. Something has definitely changed in this release.

**Comment by dev-kasibhatla** [comment]
The person who got these errors is running Version `1.0.2 (release-16-08-20-12_41_39)`
I really don't see a pattern here. The conditions are vaguely specific.

**Comment by dev-kasibhatla** [comment]
> Do you mean the Order placed successfully dialog doesn't appear at all or does the order just not appear in the Orders section?

The success dialog appears
It gets correctly recorded in firebase
Order doesn't appear in app.

**Comment by msvamp** [comment]
> It gets correctly recorded in firebase
> Order doesn't appear in app.

Interesting behaviour. Is there any error in logcat while trying to read the orders from Firebase? Is there any difference in the data of the 2 orders in Firebase apart from timestamp, items and the other obvious things?

**Comment by dev-kasibhatla** [comment]
I'm quite sure that is the case
I skip the entry on exception rn and log it. But i went through all fields of those 5 orders and couldn't spot anything fishy anywhere (with just my naked eye)
The problem is, he isn't a power user and i can't ask him for a logcat

So here's what I'm going to do;
Instead of printing everything on console (which is very wrong in a production), I'm going to print everything in ram (only for now), and add an option to submit bugreport, which will hash the logs and put it on firebase.

**Comment by dev-kasibhatla** [comment]
To save Ram, i can limit the number of entries. Say last 50 or 100 log entries only

**Comment by dev-kasibhatla** [comment]
Solved
