### ISSUE TITLE
Make ui changes for Vegetables kit 

### ISSUE THREAD

**Issue by Shree-hari** [dev-kasibhatla/krissues#7]
![Screenshot_20200814-200504](https://user-images.githubusercontent.com/31119605/90260787-a2a6e380-de69-11ea-9da3-377deeaa2529.png)
It's too much to digest for a user , actually not a good ui experience.

**Comment by dev-kasibhatla** [comment]
So how should it be done?

**Comment by Shree-hari** [comment]
> So how should it be done?

You can use the tags like style which you have used just under the search bar in the image for vegetables kit contents

**Comment by dev-kasibhatla** [comment]
We're adding a description field to every vegetable to keep the name short.
It'll be done soon.
