### ISSUE TITLE
Notification bar Overlapping the app

### ISSUE THREAD

**Issue by ShantanuVidwans** [dev-kasibhatla/krissues#9]
![Screenshot_2020-08-13-17-50-42-866_com inator Krushinavakalpana](https://user-images.githubusercontent.com/49361828/90263180-ed762a80-de6c-11ea-9c6b-10424da022c1.jpg)

MIUI 11 6 inch screen

The Notification bar should disappear or the app extend till lower edge of Notification bar

**Comment by dev-kasibhatla** [comment]
It is not really overlapping content, it is overlapping background.
I'll wrap it in a `scaffold` to avoid that

I don't think making the notification bar disappear is the appropriate behaviour for this app. It should only be done for apps where you consume media full screen or play a game.
